timeout_min: 120
cpus_per_task: 16
gpus_per_node: null
tasks_per_node: 1
mem_gb: 16
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: cpu-short
comment: null
constraint: null
exclude: null
cpus_per_gpu: null
gpus_per_task: null
mem_per_gpu: null
mem_per_cpu: null
signal_delay_s: 120
max_num_timeout: 0
additional_parameters: {}
array_parallelism: 256