method_name: snrmcmc
run: sbivibm.runs.benchmark_snrmcmc
device: cpu
params:
  num_rounds: 1
  neural_net: resnet
  hidden_features: 50
  simulation_batch_size: 1000
  training_batch_size: 1000
  num_atoms: 10
  automatic_transforms_enabled: true
  mcmc_method: "slice_np_vectorized"
  mcmc_parameters:
    num_chains: 100
    thin: 10
    warmup_steps: 100
    init_strategy: sir
    sir_batch_size: 1000
    sir_num_batches: 100
  z_score_x: true
  z_score_theta: true
  variant: B