# @package _global_

defaults:
  - override /task: two_moons
  - override /method: snrvi

task:
  vi_parameters:
    loss: elbo
    num_components: 3
    num_flows: 2
    n_particles: 86
    max_num_iters: 1000
    min_num_iters: 500
    bound: 15
    count_bins: 15
    eps: 5e-6